### ISSUE TITLE
Naming of binary (enchant-2 vs enchant)

### ISSUE THREAD

**Issue by rnkn** [rrthomas/enchant#192]
Dear Reuben,

Thank you for your work getting Enchant to work with Emacs.

I ran into a little issue when installing on macOS via Homebrew while trying to get AppleSpell to work with Emacs.

When setting the Enchant binary `enchant-2`, Emacs [looks for a binary](https://github.com/emacs-mirror/emacs/blob/master/lisp/textmodes/ispell.el#L1198-L1204) named `enchant-2-lsmod`, however the associated binary is called `enchant-lsmod-2`. 

Rather than trying to get `ispell.el` patched, I suggest naming the binary either `enchant` or linking both `enchant` and `enchant-2`.

I've [reported to Homebrew](https://github.com/Homebrew/homebrew-core/issues/25348), but was directed to you.

**Comment by rnkn** [comment]
p.s. I manually solved this by creating my own symlinks, I just figure it would be better without this user intervention.

**Comment by rrthomas** [comment]
This should be fixed in Emacs. The suffixes are a PITA in the first place (they exist for parallel installation of different versions of Enchant, for the benefit of applications using the libraries directly), but the scheme to add them is at least standard. I'm not sure why you wouldn't try to get `ispell.el` patched? In any case, since I wrote the enchant code in `ispell.el`, I can fix it.

**Comment by rrthomas** [comment]
(I am quite busy at present, so if you were to come up with a patch for `ispell.el` that I could install, that would be great.)

**Comment by rnkn** [comment]
In my experience trying to get anything in Emacs patched is like the US passing gun control.

**Comment by rrthomas** [comment]
That's why I suggested you come up with a patch and let me install it. But never mind, it's pretty simple, so I've done it.

**Comment by rnkn** [comment]
Cool 👍
