### ISSUE TITLE
Testing French replaces some tests for English

### ISSUE THREAD

**Issue by PanderMusubi** [rrthomas/enchant#231]
Please consider the following two situations when a build is tested with `make check`:
1. With only Hunspell dictionary `en_US` installed
2. With Hunspell dictionaries `en_US` and `fr_FR` installed

In situation 1) in https://github.com/AbiWord/enchant/blob/master/tests/enchant_providers/Dictionary/dictionary_suggest.cpp#L160 the following challenge is encountered https://github.com/nuspell/enchant/blob/master/tests/enchant_providers/Dictionary/dictionary_suggest.cpp#L170 where a suggestion from Nuspell can start with a lower case character.

In situation 2) this challenge is not encountered as that specific test is run on `fr_FR` where all suggestions start with a character in upper case.

Testing with situation 2) should test wider then situation 1), but for this specific case, a bug can slip through.

A work around is the following:
- Run `make check` on situation 1
- Run `make check` on situation 2

But that requires for each check to manually remove and install the French dictionary. In order test more thoroughly, please run this test for suggestions on both dictionaries when both are installed. Perhaps even run also other test for both dictionaries in order to catch language dependent bugs.

**Comment by rrthomas** [comment]
Thanks for the explanation. I believe that the different result occurs because the default dictionary used is non-deterministic (`GetFirstAvailableDictionary` is used, which just gets the first dictionary from `provider->list_dicts`). It just so happens that in this situation, the French wordlist appears to come first when installed.

I think a better method is for `GetFirstAvailableDictionary` to first try to get a dictionary for `enchant_get_user_language()`, and if that fails (for example, with the dummy providers that provide only nonsense languages), then fall back to the first available dictionary; also, rename the method `GetDefaultDictionary`.

Then, the tests can be run with the user's language set to both `en_US` and `fr_FR` (and potentially other languages too).

(As an aside, I also notice that currently the French-specific tests are not being run on Travis. I will fix that.)

**Comment by PanderMusubi** [comment]
Thanks for your reply. A while back, I had also other dictionaries installed, and they were indeed used in the testing.

In order to make the tests deterministic and easily reproducible, I'd like to propose that:
- minimally is installed `en_US` (e.g. from `hunspell-en-us`) and `fr_FR` (e.g. from `hunspell-fr-comprehensive`)
- dictionaries are loaded explicitly where possible
- where it might be possible to do a test with both dictionaries, the test is run on both dictionaries

**Comment by rrthomas** [comment]
I think that our suggestions are entirely compatible. I would prefer not to hard-wire language choices into the tests, so that it's easy to test with any desired language, as that can be useful. However, by using a predictable order, it is possible for the Travis tests (for example) to work exactly as you describe. In other words, the test environment should dictate (or at least, be able to dictate) the language or languages used. So I think I'll implement my suggestion, and then set it up to test with `LANG` set to `en_US` and then  `fr_FR`.

**Comment by PanderMusubi** [comment]
I added this to my own test process for now https://github.com/nuspell/nuspell/wiki/Enchant-integration#4-build-and-test-enchant
