### ISSUE TITLE
Document how `enchant_get_user_config_dir` works

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#239]
Specifically, that it defaults to `ENCHANT_CONFIG_DIR`. Add documentation to `enchant-provider.h`, where the function is declared.

**Comment by kckaiwei** [comment]
I followed your thread over from the pyEnchant issue, and as you mentioned:

> In both cases, dictionaries can be stored under USER_CONFIG_DIR/PROVIDER_NAME/, for example ~/.config/enchant/hunspell. By USER_CONFIG_DIR I mean the return value of enchant_get_user_config_dir(), which defaults to the environment variable ENCHANT_CONFIG_DIR.

I assume in this case, ENCHANT_CONFIG_DIR=~/.config/enchant ?

That being the case, I've tried exporting ENCHANT_CONFIG_DIR=~/.enchant with a directory called ~/.enchant/hunspell holding a bunch of myspell dictionaries. not having much luck with enchant-lsmod-2, which returns nothing

**Comment by rrthomas** [comment]
`ENCHANT_CONFIG_DIR=~/.config/enchant` is the default (or more specifically, `g_get_user_config_dig()`'s subdirectory `enchant`, no need to set it in this case. `~` will not be expanded, so that could be why it doesn't work for you. Also, the dictionaries should be named e.g. `en_GB.dic` etc.

**Comment by kckaiwei** [comment]
Sorry to bother you, but I seem to still be having issues getting dictionaries to be detected.

I've tried both via ENCHANT_CONFIG_DIR:
```
echo $ENCHANT_CONFIG_DIR
/app/.config/enchant
```

And I've gone and made a myspell + hunspell folder in there, each with a bunch of dictionary files such as `en_US.dic, en_US.aff, etc`

However, running `/app/enchant/bin/enchant-lsmod-2 -list-dicts` gives nothing (it's installed in app due to being hosted on heroku)

I've also gone and tried:
```
./configure --prefix=$HOME/enchant --with-hunspell-prefix=$BUILD_DIR/vendor/hunspell --with-myspell-prefix=$BUILD_DIR/vendor/myspell
```
which is actually saying `configure: WARNING: unrecognized options: --with-aspell-prefix, --with-hunspell-prefix, --with-myspell-prefix`

although I remember reading another issue where these are set, notably, here:
https://github.com/AbiWord/enchant/issues/164

At this point, I'm kind of scratching my head trying to think of how else I can try loading the dictionaries.

Note: I am using enchant 2.2.8

**Comment by rrthomas** [comment]
I'd suggest debugging it with a breakpoint on `enchant_broker_list_dicts`. When I do that and then step into `hunspell_provider_list_dicts` (which I can't break on directly because it's loaded at runtime), I then look at `dict_dirs` when it's built (in the sources on master, this is `providers/enchant_hunspell.cpp` line 415), and the list of directories built includes (for me) `$HOME/.config/enchant/hunspell`. (I have no `ENCHANT_CONFIG_DIR` set, as it happens.)

If the relevant directory is not getting included in your list, you can take a look at `enchant_get_user_config_dir`; if it is, you can see why the hunspell backend is ignoring the dictionaries you have there.

`strace` might also help. Sorry if this is all rather obvious, but I can't guess based on what you've told me why it's not working.

**Comment by kckaiwei** [comment]
Got it, i'll look into that, many thanks!

**Comment by krbailey** [comment]
@kckaiwei @rrthomas I'm trying to create a package that includes my Python file performing Enchant spellcheck with a dictionary. Is it possible to bundle the two so that I don't have to install the dictionary on every pc I run the program on, but set it to reference the hunspell folder? Setting `os.environ["ENCHANT_CONFIG_DIR"] ` it isn't looking into this directory?

**Comment by rrthomas** [comment]
@krbailey, I see you've found an issue against `pyenchant`, that seems to be a better place to start.

I observe with PyEnchant 3.2.0 that:

```python
>>> import enchant
>>> enchant.get_user_config_dir()
/home/rrt/.config/enchant
>>> import os
>>> os.environ["ENCHANT_CONFIG_DIR"] = '/nonexistent'
>>> enchant.get_user_config_dir()
/nonexistent
```

So the setting seems to work.

**Comment by krbailey** [comment]
Right, I had been using that but, it would not search that config directory that I set, I'll move to the pyenchant github, Thanks

**Comment by rrthomas** [comment]
@krballey, thanks! I am keen to hear if it does seem after all to be an Enchant bug, and if I can find some time, I'll do some tests of my own.

**Comment by rrthomas** [comment]
OK, I set up a directory, added a `hunspell` subdirectory, copied a Polish dictionary in there (I have no Polish dictionary installed on my system), and set `ENCHANT_CONFIG_DIR`. `enchant-lsmod-2 -list-dicts` showed Polish as an option.

I unset `ENCHANT_CONFIG_DIR` in my shell, started ipython, set `ENCHANT_CONFIG_DIR` again with `os.environ`, imported `enchant` and created a Polish dictionary.

So, it all seems to be working!

**Comment by krbailey** [comment]
Thanks for looking into it. I followed those steps but with pyenchant but for some reason it isn't recognizing any dictionaries even if I add them to the /.config/enchant/hunspell directory or set a custom directory. I'll keep playing with it though
