### ISSUE TITLE
Faster build system

### ISSUE THREAD

**Issue by dimztimz** [rrthomas/enchant#301]
This may seem controversial, but the truth is that the current build process is super slow. Replacing Autotools with CMake will speedup the build 100 times. That is impossible right now because of Gnulib, which has hard dependency on Autotools. Removing just Gnulib would speedup the building noticeably. Enchant uses the following modules:

https://github.com/AbiWord/enchant/blob/49d87fea52bb19770f76710cfaf69881246a7219/bootstrap.conf#L49-L60

Of them only the module "relocatable" is useful, all others are part of POSIX and are available on all relevant platforms.

- Relocatable can be copied directly from Gnulib just by copying `relocatable.h` and `relocatable.c`.
- Flock can be achieved by reverting this commit edf662a5ec8db85aa6e5a5d00531ab6b8773131f.
- Strchrnul is not available on MinGW but it can be easily replaced with the standard `strchr`.

Are you interested in doing this?

**Comment by rrthomas** [comment]
Thanks very much for looking into this. I have to say, the speed of the build process doesn't bother me. In particular, it's only really slow a) from git b) in a fresh checkout (e.g. in CI). I use parallel make, ccache, a pre-checked out gnulib and cached `configure` results and re-building in a development tree rarely takes a long time, even when I have to reconfigure or re-bootstrap. On my old 2014 MacBook Pro, even a fresh checkout takes only 73 seconds to build. (On my Ryzen 3700 it took 60s including the tests!) So is there some particular situation you feel needs improving?

I have nothing against CMake but my ignorance: I would not be able to maintain a CMake-based build system without a lot of work learning CMake. Also, CMake itself is something people seem to be migrating away from; going from autotools to CMake feels rather like going from Subversion to Mercurial.

Finally, thanks for doing the work on analysing the use of gnulib. I agree that most of it is not needed on most systems; but the good thing about using gnulib is that I don't have to care about that: I just use gnulib, and it takes care of things that don't work. I am constantly surprised by how people build things on old versions of OSes (e.g. ancient macOS, for MacPorts came up recently, when I was trying to help fix a bug in gnulib). Also, it's not just the APIs; the tools for e.g. linting the code are very useful. Again, I'm sure they could be replaced, but it would be more work.

So I guess the answer is: I am not keen on this. I think it's probably easier to speed up the build in most cases, and if CMake were used it would need a new co-maintainer, at least.

**Comment by dimztimz** [comment]
> even a fresh checkout takes only 73 seconds to build. (On my Ryzen 3700 it took 60s including the tests!) So is there some particular situation you feel needs improving?

With Cmake the build would take 5 seconds.

> I have nothing against CMake but my ignorance: I would not be able to maintain a CMake-based build system without a lot of work learning CMake.

Once you go to CMake you would never turn back to Autotools. The Cmake scripts will be around 10 times smaller than the Autotools scripts. True, there is some learning curve.

> Also, CMake itself is something people seem to be migrating away from; going from autotools to CMake feels rather like going from Subversion to Mercurial.

This isn't true. Cmake is both the fastest and the build system with most features, and right now it is the most used build system for C and C++. There are some people on the Internet that complain, as usual. There is the old saying "There are only two kinds of languages: the ones people complain about and the ones nobody uses.”.

> how people build things on old versions of OSes (e.g. ancient macOS, for MacPorts came up recently, when I was trying to help fix a bug in gnulib).

You should not bother supporting OSs that are not supported by their manufacturer. For example Apple's oldest supported macOS right now is 10.15. 10.14 is unsupported right now.

> So I guess the answer is: I am not keen on this. I think it's probably easier to speed up the build in most cases,

We can try to speedup the build without migrating to Cmake. One should do one or more of the following:

1. Stop using gnulib via git and start using it from an OS package, for example https://packages.ubuntu.com/focal/gnulib . The package has all the Gnulib modules and gnulib-tool.
2. Commit the used gnulib modules inside the source tree. Right now they are ignored via `.gitignore`. I think you are using solution number 2 described here https://www.gnu.org/software/gnulib/manual/html_node/VCS-Issues.html.
3.  Reduce the used modules. At least these four can be removed without much thinking:  c99, getopt-posix, strdup-poisx, ssize_t.
4. Completely drop gnulib and copy from it only what is most necessary while still using Autotools.

**Comment by rrthomas** [comment]
> With Cmake the build would take 5 seconds.

Being faster is not really a big attraction. I was really asking, is something slow for you? Most of my rebuilds are only 5s, and most of my slow builds are CI, which don't waste my time. That said, 5 seconds is nice!

> Once you go to CMake you would never turn back to Autotools. The Cmake scripts will be around 10 times smaller than the Autotools scripts. True, there is some learning curve.

For comparison, the current build system is about 600 lines (that's `bootstrap.conf`, `configure.ac` and all the `Makefile.am` files).

> This isn't true. Cmake is both the fastest and the build system with most features, and right now it is the most used build system for C and C++.

That's good to know (and I confirmed it with a little research).

> You should not bother supporting OSs that are not supported by their manufacturer. For example Apple's oldest supported macOS right now is 10.15. 10.14 is unsupported right now.

As I said, MacPorts supports older versions. I asked about this and I was convinced by the reply: Apple does not support older machines, so the users do instead. I am in general more interested in what users want than what manufacturers support.

And of course, autotools and gnulib have good support for rare OSes that I don't know about. My experience with CMake is that you have to support each OS explicitly, which is not good for a portable project.

> We can try to speedup the build without migrating to Cmake. One should do one or more of the following:
> 
>     1. Stop using gnulib via git and start using it from an OS package, for example https://packages.ubuntu.com/focal/gnulib . The package has all the Gnulib modules and gnulib-tool.

No change is required to do this, it's just a matter of setting `GNULIB_SRCDIR` in the environment.

>     2. Commit the used gnulib modules inside the source tree. Right now they are ignored via `.gitignore`. I think you are using solution number 2 described here https://www.gnu.org/software/gnulib/manual/html_node/VCS-Issues.html.

I am not a fan of committing generated files/files from other projects. But if you'd be prepared to measure the difference in speed and it's compelling, then I would certainly consider it.

>     3. Reduce the used modules. At least these four can be removed without much thinking:  c99, getopt-posix, strdup-poisx, ssize_t.

I would be happy to remove modules for features that are required by C99 and POSIX 2008, and would certainly accept a PR for that.

>     4. Completely drop gnulib and copy from it only what is most necessary while still using Autotools.

For me, gnulib is one of the best things about autotools!

I really wish that libposix was a thing (that is, a build of gnulib as a normal binary library with headers). Unfortunately it has been stalled for a long time. If someone would work on that it would be amazing.

**Comment by dimztimz** [comment]
After some tinkering I decided it is pointless to improve the build system with Autotools + Gnulib. It is simply too much entangled web. What I may offer at some point in the future are Cmake scripts. I have some initial prototype and it is much simpler code than Autotools and builds in less than 5 seconds.

Why I opened this issue in the first place? Well, full build on Linux may take only few minutes and that may not seem slow (IMO even that is slow), full build on Windows + MinGW takes 15-20 minutes.

**Comment by rrthomas** [comment]
Thanks very much for trying, and I would certainly consider a CMake build system PR. If it's a tenth of the size of the current one and has the same functionality, then I would probably be happy with the overhead (and opportunity!) of learning more about CMake.

I had a look at GitHub actions (the interface is a great improvement on AppVeyor!) and it suggests that gnulib alone is not a big part of the problem on Windows. (I'm assuming that extra build time due to gnulib can be mostly discounted, as for POSIX modules code is only compiled on systems that need it.) By far the longest step is "make distcheck". As I understand it, autotools-based build systems are slow on Windows mainly because of the vast number of processes spawned, which is much less efficient than forking on non-Windows systems. Obviously, using CMake would help here.

Just running the minimal `./configure && make && make check` on Windows takes about 6 minutes. It would be possible to publish a source tarball for every commit, allowing this faster route.

I also don't understand why using the gnulib package would not be a win on Ubuntu; but looking at GitHub Actions for Ubuntu, running `bootstrap` only takes 19s in any case, so it wouldn't be a big win.

Finally, forgive me if I'm being obtuse, but I still don't understand the use case for which you're trying to speed up the build. 20-25 minutes is a long time, but for CI it doesn't really matter (to me, at least). If one is working on Windows for development, builds are much faster (for occasional Windows debugging, I have no problem with the build speed, even on a VM).

**Comment by dimztimz** [comment]
Hacking on Windows is real pain. Mostly because things are really slow. The edit-build-test cycle is terrible. The waiting for 6 minutes is the best case. One often needs to reconfigure. Cmake is the way to go. While Autotools may support ancient Unixes, Cmake properly supports Windows and all other modern Unixes.

I discovered another source of slowness (on any OS) and that is the call `make check`. All calls fully rebuild the test suite, but that should not happen. Only the first call to make check should build the tests, others just need to rerun them.

**Comment by rrthomas** [comment]
> The waiting for 6 minutes is the best case.

I can't reproduce this in the case of a simple code edit.

> One often needs to reconfigure.

As I said before, use a configure cache.

> I discovered another source of slowness (on any OS) and that is the call `make check`. All calls fully rebuild the test suite, but that should not happen. Only the first call to make check should build the tests, others just need to rerun them.

I can't reproduce this: the providers tests are remade, which takes insignificant time, but not the main tests.

**Comment by dimztimz** [comment]
Ok I will close this, maybe I can get back to it some another day.

**Comment by rrthomas** [comment]
Thanks. You've at least encouraged me to see what can be done with other build systems such as CMake. I shall try to look into that for one or two personal projects.

**Comment by dimztimz** [comment]
Are you willing to push this a little further? I can send you some less controversial patches as PR that reduce dependency on Gnulib, i.e. the easier ones.

**Comment by rrthomas** [comment]
Sure!

**Comment by LecrisUT** [comment]
@rrthomas @dimztimz I would like to encourage a re-visit of the CMake migration:
- unfortunately any backend migration will require a big PR. I can help review a PR, or help modernize one, but it would require some feedback from the developers on what dependencies, features, etc. are needed
- there are additional benefits for a cmake migration, let me enumerate a few that I could help design:
  - better dependencies detection. Detect cmake, pkg-config, or plain libraries in an OS agnostic manner
  - better downstream integration. The project can be imported directly like a git clone, but also other cmake (and even other backends) projects can pick up the project installed on the system. The main target I see here is for something like python bindings (using scikit-build-core)
  - better testing environment. Can also make the tests portable so that it tests the versions installed on the system
  - dynamic versioning like `setuptools-scm`. This is from a personal project of mine
- I do not have experience with windows packaging unfortunately so I can't comment much there
- regarding the meson proposal, having a CMake build system would guarantee meson projects can [import it](https://mesonbuild.com/CMake-module.html). Unfortunately the other way around is not currently possible on cmake side

For reference [here](https://github.com/LecrisUT/CMake-Template) is my cmake template/project design

**Comment by rrthomas** [comment]
I've not found the opportunity to experiment with CMake myself, unfortunately (I've mostly been working in Python and TypeScript in the last year), but I would still look favourably on a PR.

**Comment by dimztimz** [comment]
> I've not found the opportunity to experiment with CMake myself, unfortunately (I've mostly been working in Python and TypeScript in the last year), but I would still look favourably on a PR.

A precondition to moving toward CMake is removing Gnulib. You refused to do that in the past at least two times. Have you changed your mind on that?

**Comment by LecrisUT** [comment]
I am not familiar with gnulib, but this is an example where a bit of collaboration from the main developer would help:
- what is gnulib used for?
- are there alternative software that do similar tasks?
- how do you call it at the configure/build/install stage?

Depending on that we can provided simpler cmake native functionality or we can make a wrapper for it (like swig or bison/yak).

But as said I am not familiar with gnulib, but I can offer a second opinion on whether or not it is a hard requirement, or if there are better alternatives to migrate towards.

**Comment by rrthomas** [comment]
> I am not familiar with gnulib, but this is an example where a bit of collaboration from the main developer would help:

Sure thing!

>      * what is gnulib used for?

A mixture of build system and library functions. Gnulib is modular, and you can see which modules are used in `bootstrap.conf` in the list `gnulib_modules`. Thanks to @dimztimz the list is now quite short.

>     * are there alternative software that do similar tasks?

For the build system, CMake presumably has similar functionality and/or plugins/add-ons.

For the library routines, I would prefer one of the following: either use more GLib routines, or use C++ standard library routines. The main code is currently in C, but since we require C++ for multiple back-ends, there's no problem if some of it is rewritten.

The hardest functionality to replace is probably the gnulib `relocatable-lib-lgpl` module, which makes Enchant relocatable to anywhere in the file system (or "portable" in Windows speak).

>     * how do you call it at the configure/build/install stage?

Unfortunately, gnulib really depends on GNU autotools.

> But as said I am not familiar with gnulib, but I can offer a second opinion on whether or not it is a hard requirement, or if there are better alternatives to migrate towards.

The main thing is that I don't want to introduce new dependencies. Glib is already "big enough" a dependency IMO. Since gnulib is a source library, the functions that Enchant uses from it are included as source, and there's no extra build dependency. The code is also widely used in other GNU projects such as coreutils, so it's pretty well tested.

Hence, my suggestion to use either GLib or C++ std functionality instead, as we already require both of those.

**Comment by LecrisUT** [comment]
> > The hardest functionality to replace is probably the gnulib relocatable-lib-lgpl module, which makes Enchant relocatable to anywhere in the file system (or "portable" in Windows speak).

> As long as there are no hard-coded paths, CMake does it by default.

I'm not sure how that would work. Enchant can currently be moved from one place to another in the file system, and it "Just Works": it is able to find files relative to the main library at run-time thanks to the gnulib routines. If CMake has an equivalent bit of C code, that would be great, of course!

> Unfortunately, gnulib really depends on GNU autotools.

> - does it generate source code like yak, bison, swig, etc.

Yes.

> - does it provide libraries dependent on OS?

Yes.

> - does it provide flags and configure/build options?

Yes.

> My rule of thumb is if the feature is available in the most recent LTS distro, then make use of it.

I prefer to be a bit more conservative with Enchant, as it is widely used e.g. by applications that build new versions for older OSes. But in any case, I've never found it a problem, as Enchant never needed the latest library features while I've been maintainer.

>  Just consider what project could help simplify the most and I can give a review on those.

Thanks for the offer; I'm not sure what you're suggesting you could do here, though?
