### ISSUE TITLE
Word splitting differs in aspell's standalone program

### ISSUE THREAD

**Issue by astoff** [rrthomas/enchant#316]
I get different results if I call aspell directly or via the enchant CLI:

```
$ aspell -d en_US -a
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
well-known
*
*

$ enchant-2 -d en_US -a
@(#) International Ispell Version 3.1.20 (but really Enchant 2.3.4)
well-known
& well-known 11 0: welkin, Wilkinson, welkin's, Walkman, weakening, walking, Wilkins, welcoming, Wilkerson, Wilsonian, lignin

```

Is this intentional?

**Comment by rrthomas** [comment]
I'm sorry, the answer is "it's complicated". Enchant may not use aspell's library in exactly the same way as aspell's front-end does.

I can reproduce the behaviour you show. A little debugging suggests that this occurs because Aspell's front-end parses "well-known" as two words, each of which checks as correct, while Enchant parses it as a single word, which is not in Aspell's dictionary. Meanwhile, if I use the hunspell back-end, Enchant parses "well-known" as two words.

The reason for this is that Hunspell's Enchant back-end has its own rule for which characters are allowed in a word (`hunspell_dict_is_word_character`), which is partly based on information encoded in the word-list (the `getWordchars` method), whereas Aspell does not, so Enchant uses its built-in definition for that case.

Aspell's tokenization algorithm is quite simple, but it depends on the character set in use. For US English, hyphen is not a special character, and is not a word character, and as far as I can tell it's therefore not counted as part of a word.

Unfortunately, Aspell's tokenizer is not exposed in the API; rather, it assumes that it will be fed lines or strings of text to tokenize. Therefore, it would not be easy to use it directly from Enchant's front-end, which assumes responsibility for tokenization itself.

I'm sorry, I'm not sure there's much to be done here without considerable extra complication, given that Enchant cannot directly access Aspell's "is a word character" predicates, as for Hunspell's simpler case.

**Comment by astoff** [comment]
Okay, thanks for the explanation! It seems enchant is indeed proceeding in the most reasonable way. I'll close the issue in this case.
