### ISSUE TITLE
How to feed parameters to programs

### ISSUE THREAD

**Issue by walseb** [rrthomas/enchant#321]
Hello!

I'm an avid user of Aspell, and so have accumulated many parameters that I give it on startup.

How would I feed Aspell parameters through the enchant CLI? For instance: `--sug-mode=bad-spellers`

I can't find any information on how I would go about this in the manual

Perhaps I could do it by creating an Aspell config? Will Aspell read its own config when launched through enchant? 

I would prefer to set the parameters through the CLI however, as I have several custom parameters that run depending on the language I'm writing in. Perhaps you could specify what parameters to run with what language somewhere in the Aspell config.

Thank you for this package, and thanks for any help!

**Comment by rrthomas** [comment]
In short, you can't.

The Enchant CLI uses `libenchant` which in turn uses `libaspell` (in the case where you have selected Aspell for the language you're checking). So the `aspell` CLI is never used.

I had a think about what might make sense to implement. I think it depends on the particular functionality. Something that is independent of the back-end (e.g. minimum length of word considered for correction) could be implemented in Enchant itself. Other things like ASpell's `--sug-mode` would have to be implemented as a back-end specific option. For aspell, one could use the configuration values; other widely-used spelling checkers (e.g. hunspell) are not so configurable. In any case, one would not want to add a complex configuration parser to Enchant; and in general, Enchant tries to be as simple as possible (both CLI and API).

I suspect this is not going to be worth implementing as a general mechanism, because as far as I can see, Aspell is the only spelling engine that has this sort of user configuration.

So, you're probably better off using Aspell directly (I appreciate that of the programs I know that use Aspell either directly or indirectly, only Emacs allows it to be configured, so this may mean really "using `aspell` directly").

A to me more obvious approach here would be for `libaspell` to offer an API to read user configuration files. I would be happy to add support for that to Enchant.

**Comment by walseb** [comment]
Ah, I see!

Thank you so much for the in-depth answer!

**Comment by rrthomas** [comment]
You're welcome! Closing this issue, but I would be happy to consider contributions along the lines I sketched above.
