### ISSUE TITLE
propagate error messages from aspell 

### ISSUE THREAD

**Issue by solodov** [rrthomas/enchant#350]
I managed to add a word with a weird quote to my personal dictionary:

```
foo’s
```

This breaks aspell:

```
$  echo test | aspell --lang=en_US list
Error: /Users/blah/.aspell.en.pws: The word "foo���s" is invalid. The character '�' (U+80) may not appear in the middle of a word.
```

This error message is descriptive enough. Enchant, however, fails without a useful explanation:

```
$ enchant-lsmod-2 -lang en_US

(process:84044): libenchant-CRITICAL **: 19:32:49.356: enchant_provider_set_error: assertion 'g_utf8_validate(err, -1, NULL)' failed

(process:84044): libenchant-CRITICAL **: 19:32:49.357: enchant_provider_set_error: assertion 'g_utf8_validate(err, -1, NULL)' failed
No dictionary available for 'en_US'
```

It would be very helpful if enchant could provide an error message similar to aspell.

**Comment by rrthomas** [comment]
Good idea!

**Comment by rrthomas** [comment]
There are two problems here. First, the error message from aspell is invalid UTF-8, and Enchant tries to validate it. I am minded to remove this validation, and warn in the API that error messages may not be valid UTF-8.

The second problem is that an error message does not necessarily mean that something is wrong. Aspell will return an error message if a dictionary for a given language is not found, but that's not necessarily an error for Enchant, as it will see if some other provider can provide such a dictionary.

So the question is, when should the error message be printed? Enchant has no way to know that something is "unusually wrong" (as in this case), rather than "normally wrong" (as when a particular spelling provider lacks a dictionary for a particular language).

In the case of just using aspell, the case is clear: there's only one provider, so any error is a "real" error.

I can certainly output the error when no dictionary is available at all for the language, as in this case (also in `enchant` as well as `enchant-lsmod`).

I think the best I can do in the general case is output a debug message (that can be made visible with `G_MESSAGES_DEBUG`).
