### ISSUE TITLE
Fix custom dictionary support

### ISSUE THREAD

**Issue by tecosaur** [rrthomas/enchant#358]
I have a custom dictionary installed for aspell and hunspell by the name of `en-custom` created by http://app.aspell.net/create.

I can confirm that this works with aspell and hunspell, but it seems like enchant doesn't pick it up?

```
~$ cat /tmp/word.txt | aspell -d en-custom list
~$ hunspell -l -d en-custom /tmp/word.txt
~$ enchant-2 -l -d en-custom /tmp/word.txt
alkalinisation
archiphoneme
arcsecond
bicuspidate
```

Trying the dictionary listing commands of aspell, hunspell, and enchant, this is what I see:

```
~$ aspell dump dicts
en
en-custom
en-variant_0
en-variant_1
en-variant_2
en-w_accents
en-wo_accents
en_AU
en_AU-variant_0
en_AU-variant_1
en_AU-w_accents
en_AU-wo_accents
en_CA
en_CA-variant_0
en_CA-variant_1
en_CA-w_accents
en_CA-wo_accents
en_GB
en_GB-ise
en_GB-ise-w_accents
en_GB-ise-wo_accents
en_GB-ize
en_GB-ize-w_accents
en_GB-ize-wo_accents
en_GB-variant_0
en_GB-variant_1
en_GB-w_accents
en_GB-wo_accents
en_US
en_US-variant_0
en_US-variant_1
en_US-w_accents
en_US-wo_accents

~$ hunspell -D
SEARCH PATH:
.::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/Library/Spelling:/home/tec/.openoffice.org/3/user/wordbook:/home/tec/.openoffice.org2/user/wordbook:/home/tec/.openoffice.org2.0/user/wordbook:/home/tec/Library/Spelling:/opt/openoffice.org/basis3.0/share/dict/ooo:/usr/lib/openoffice.org/basis3.0/share/dict/ooo:/opt/openoffice.org2.4/share/dict/ooo:/usr/lib/openoffice.org2.4/share/dict/ooo:/opt/openoffice.org2.3/share/dict/ooo:/usr/lib/openoffice.org2.3/share/dict/ooo:/opt/openoffice.org2.2/share/dict/ooo:/usr/lib/openoffice.org2.2/share/dict/ooo:/opt/openoffice.org2.1/share/dict/ooo:/usr/lib/openoffice.org2.1/share/dict/ooo:/opt/openoffice.org2.0/share/dict/ooo:/usr/lib/openoffice.org2.0/share/dict/ooo
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/usr/share/hunspell/en_US
/usr/share/myspell/en_US
/usr/share/myspell/hyph_en_US
/usr/share/myspell/en-custom

~$ enchant-lsmod-2 -list-dicts
en (aspell)
en_AU (aspell)
en_CA (aspell)
en_GB (aspell)
en_US (aspell)
```

#### Version information
- Enchant 2.6.7
- Aspell 0.60.8.1
- Hunspell 1.7.2

**Comment by tecosaur** [comment]
Following https://abiword.github.io/enchant/src/enchant.html, I've tried putting `en-custom.multi` and `en-custom.rws` under:

- `~/.local/enchant/aspell`
- `~/.local/enchant`
- `~/.local/enchant-2/aspell`
- `~/.local/enchant-2`
- `~/.config/enchant/aspell`
- `~/.config/aspell`

Yet with none of the above did the dictionary `en-custom` show up.

**Comment by rrthomas** [comment]
I am getting really fed up with these "why can't Enchant find my custom dictionary?" issues, so I can only imagine how fed up users are. I'm so sorry!

I shall look into this and report back.

**Comment by rrthomas** [comment]
So, the situation is that the custom directory support for `.config/enchant/PROVIDER` in fact only works for `.config/enchant/hunspell`. I made a custom dictionary using the site you mentioned, installed it in the Enchant user directory, and it works fine. (Maybe you forgot to use a Hunspell dictionary for the `hunspell` directory when you tested?)

For other providers, the situation is as follows:

- aspell: we can use the `local-data-dir` configuration element to set an extra directory. This is a little unsatisfactory, as it will override any setting the user has made (we can only set one directory this way). As with hspell (see below), I guess we could abuse this setting slightly: if we get Aspell to list its dictionaries without changing this setting, and then again with the setting changed, then we can find both Aspell user-specified dictionaries *and* Enchant user-specified dictionaries.
- hspell can only see one dictionary at a time, but it has an API `hspell_set_dictionary_path` that could be used to list/load user-installed dictionaries.
- nuspell can accept extra paths, so that's fine.
- voikko can accept an extra search directory, so that is enough for Enchant.
- Zemberek I'm not going to worry about. Its provider back-end remains experimental, and I've never heard from users. (If anyone reads this and would like to help out, I'd love to hear from you!)

So it should be possible to add the same functionality as for Hunspell for Nuspell and Voikko with no problems, for Aspell easily if we overwrite Aspell's own user setting, and for Aspell "fully" and Hspell with a bit of extra work.

So I think the first step is to document the current situation properly and make a new release, so that at least users can find out the lack of support without thinking they are doing something wrong. Next, I will add the easy cases above: Nuspell, Voikko, and Aspell-with-Enchant-override. Finally, I'll see about the harder cases.

Change of plan: Aspell turns out to be trickier than I thought, even in "easy mode", while Hspell was easier.

- [x] Document lack of support for Enchant user dictionaries
- [x] Support Enchant user dictionaries for Hspell, Nuspell, Voikko
- [ ] Support Enchant user dictionaries for Aspell

**Comment by rrthomas** [comment]
2.6.8 (out shortly) will at least document the current limitations, and hopefully thereby avoid some frustration for users.

**Comment by tecosaur** [comment]
Thanks for looking into this! The extra clarity would have been a big help, and it would be great to see support for a consistent "custom dict" method across the various spellcheck providers.

**Comment by kevina** [comment]
@tecosaur I _think_ enchant is using the "en" or "en_US" dictionary and not "en-custom".  You might be able to get around this by using the "variety" config option.  For example:
```
ASPELL_CONF="variety custom" enchant-2 -l -d en /tmp/word.txt
```

**Comment by rrthomas** [comment]
@kevina thanks for the hint. That might be an extra problem; the problem I identified (that custom dictionaries in `~/.config/enchant/aspell` won't be seen by the Aspell backend) does exist, and I've fixed it in git (on "easy mode" above; I've emailed you to ask about the best approach for a full fix).

**Comment by kevina** [comment]
@rrthomas oops I meant to ping @tecosaur.  I already replied to your email.

**Comment by rrthomas** [comment]
@kevina thanks for letting me know, I dug your email out of spam (didn't look at all spammy!).

**Comment by kevina** [comment]
Based on a private email exchange with @rrthomas it looks like the issue will be solved with the latest version of Enchant.  @tecosaur please disregard my suggestion as based on my new understanding of how enchant works, I don't think it will help.

**Comment by rrthomas** [comment]
In fact, Aspell has turned out to be tricky, while Hspell was easier than I thought, so 2.6.9 (out shortly) will contain user dictionary support for Nuspell, Voikko, and Hspell, while Aspell will have to wait until I can make it work.

**Comment by rrthomas** [comment]
2.6.9 was released with custom dictionary support. Aspell support is in the works via [this issue](https://github.com/GNUAspell/aspell/issues/646) for Aspell, but since that involve an API change to Aspell, it won't be available to most users for some time.

**Comment by tecosaur** [comment]
It's been a while, but @rrthomas I just wanted to say how much I appreciate your thorough response to this issue. It's much appreciated!
