### ISSUE TITLE
Dropping older plugins

### ISSUE THREAD

**Issue by TingPing** [rrthomas/enchant#59]
I'll start off by saying these probably aren't a major problem as they are fairly low maintenance and self contained but it is probably something worth documenting.

So of the current plugins only a few of the libraries are actually actively maintained:

- voikko
- hunspell
- hspell
- zemberek

The rest are unmaintained:

- ispell
- aspell
- uspell

As I understand it aspell should effectively be a replacement for ispell and the ispell plugin is also like 1/3 of enchants codebase so it seems logical to drop that.

The aspell plugin itself is small, and the library is still shipped by distros and useful so it seems reasonable to keep.

Zemberek is a fairly poor plugin doing blocking DBus calls for everything (using the deprecated dbus-glib), always marked 'experimental' since it was added, prints that it is known to cause crashes, and as far as I can tell the Zemberek server is packaged by no distribution.

I actually couldn't find much information on uspell, so I'll just assume the worst.

At the very least I think these should be demoted from `auto` in the build system to defaulting disabled.

**Comment by hfiguiere** [comment]
uspell is now at https://github.com/AbiWord/uspell

I imported it recently from CVS.

**Comment by TingPing** [comment]
Looks like the only thing of value uspell has is a yiddish dictionary but still not very useful since nothing ships it.

**Comment by rrthomas** [comment]
Some initial thoughts on this: I agree it would be good to deprecate unused providers.

Aspell I think is unquestionably still widely used, so we should not deprecate its plugin for now. As to the others:

- uspell: we could move the provider to the uspell repo. I find no Yiddish dictionary packaged in Debian/Ubuntu, but there are dictionaries available for e.g. hunspell, so this is not a unique resource.
- zemberek: this is packaged in Debian. If we deprecate the plugin, the packagers get the choice whether to build it explicitly, or perhaps decide it's not worth it.
- ispell: I suspect there are people still using this, not least for the nroff and TeX-specific support. I'd like to change Emacs so that it only uses Enchant, and I suspect the Emacs maintainers will not agree if Enchant does not support ispell. Having said that, it's silly to have a fork of ispell in our tree, given that ispell is still maintained. I will investigate whether there's any chance of it offering a library interface. (I guess that would be C, not C++, but it should not be a lot of work to "port" our current C++ ispell interface to C, build ispell as a library, and use that interface in our provider.) In any case, the provider should be deprecated.

**Comment by TingPing** [comment]
> zemberek: this is packaged in Debian.

Are you sure? Note that we don't use the Zemberek Java library directly we depend upon a DBus server that wraps it. Which based on what I could find is third party, unmaintained, and not packaged.

**Comment by rrthomas** [comment]
The Debian package contains `/etc/dbus-1/system.d/zemberek-server.conf`, and the source package contains a `DBusClient` class. Is that not the bit you mean?

**Comment by TingPing** [comment]
Ah that would be it, apparently they just don't know what a service file is.

**Comment by rrthomas** [comment]
I contacted the ispell maintainer, who is not interested in library-ifying ispell.

I propose therefore to spin out the library part of the ispell provider (everything except the provider itself) into a separate project, and keep it in CI so that it continues to be tested.

That way, enchant will no longer be responsible for the actual spell-checking code, but it will still work, and if someone in future wants to merge it back into ispell, or otherwise maintain it, that will be straightforward.

**Comment by rrthomas** [comment]
It turns out that the ispell back-end already does not work with current dictionaries. I therefore propose to remove it for now completely.

@hfiguiere, please could you create a "libispell" repo in AbiWord please, so I can dump the old ispell back-end there?

**Comment by hfiguiere** [comment]
Have fun with https://github.com/AbiWord/libispell

**Comment by rrthomas** [comment]
Thanks very much, @hfiguiere. I've pushed the code and added a README suggesting the best way to resurrect it and encouraging anyone who wants to do so to get in touch with the Enchant maintainers.

**Comment by rrthomas** [comment]
I see that GNU Aspell had a release candidate out at the end of January!

I will deprecate the uspell and Zemberek plugins, and that will conclude my work on this issue.

**Comment by rrthomas** [comment]
Fixed by PR #103.

**Comment by PanderMusubi** [comment]
The Debian/Ubuntu package requires aspell to be installed. As hunspell is preferred over aspell, this should be more loose. The package dependency which is now

    Depends: aspell-en | myspell-dictionary | aspell-dictionary | ispell-dictionary | hunspell-dictionary,
    libaspell15 (>= 0.60.7~20110707), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libglib2.0-0 (>= 2.35.9),
    libhunspell-1.4-0, libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4)

and should become:

    Depends: aspell-en | myspell-dictionary | aspell-dictionary | ispell-dictionary | hunspell-dictionary,
    libaspell15 (>= 0.60.7~20110707) | libhunspell-1.4-0, libc6 (>= 2.14), libgcc1 (>= 1:3.0),
    libglib2.0-0 (>= 2.35.9), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4)

If you agree, I will also create a bug report at Ubuntu on this.

**Comment by rrthomas** [comment]
It's really a matter for downstream (by the way, it's better to submit the report to Debian, so the work doesn't have to propagate backwards manually, but forwards automatically). However, it certainly makes sense to me.
