### ISSUE TITLE
Build on more Windows targets

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#76]
Specifically, mingw32 and mingw64 (currently we build to MSYS2, which is the least useful).

**Comment by TingPing** [comment]
> Specifically, mingw32 and mingw64 (currently we build to MSYS2, which is the least useful).

mingw32 is dead, and msys2 is based off of mingw64.

**Comment by rrthomas** [comment]
I mean that we should do 32 and 64-bit builds of enchant. I see that now this seems to mean using two different MingW64 compilers, namely x86_64-w64-ming32 and i686-w64-mingw32.

MingW64 vs MSYS2: these take different approaches to Unix compatibility, and use different compilers. MingW64 is more important, as it's what will be used for building native Windows apps. Perhaps it would be more useful to build Cygwin than MSYS2, which does not seem to be that widely used except as a development environment?

**Comment by TingPing** [comment]
Gotcha, they are sort of loaded terms since mingw-w64 provides both 32bit and 64bit but replaces the old mingw32 project and the MSYS2 project includes mingw... ugh.

I agree testting mingw-w64 is more important than msys and I don't think cygwin is overly valuable as if it is doing its job it behaves the same as a unix env.

**Comment by rrthomas** [comment]
Haha "if it is doing its job"! Also, there is Cygwin-specific code in various places. But yes, I'll concentrate on mingw-w64.
