### ISSUE TITLE
Remove get/set_param APIs

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#98]
In `enchant.h` and `enchant-provider.h`: these 3 APIs are only used for one function, in only three backends (of which only hunspell is not obsolescent): to get the dictionary path. If a mechanism is needed for this, let it be an environment variable like everything else. (Previously these APIs were also used by the now-removed Windows-only registry APIs).

**Comment by rrthomas** [comment]
Closed by PR #100.

**Comment by eht16** [comment]
Is there any replacement available for the removed APIs?
You mentioned an environment variable but I cannot find any reference to it.

We use Enchant in a spellcheck plugin for the IDE Geany and on Windows, it is essentially important for users to be able to specify a custom path for dictionary files as Enchant would look somewhere in the directory tree of the installation path of the library itself which is pretty inconvenient due to the filesystem layout on Windows.

So, without being able to specify a custom dictionary path, Enchant becomes much more harder to be used on Windows.

**Comment by rrthomas** [comment]
See enchant(1): it's `ENCHANT_CONFIG_DIR`. (That specifies the configuration directory, not the dictionary directory itself, but dictionaries are stored under that, as in Enchant 1.)

Also, note the location for per-user configuration on Windows (again, documented in enchant(1)).

**Comment by eht16** [comment]
Ah, great. Thanks!

**Comment by rrthomas** [comment]
You're welcome. If you have any insight into how I can make the documentation more obvious than "put it in the principal man page", I'd love to hear it!

**Comment by eht16** [comment]
Maybe provide generated API docs in HTML format and add some basic usage instructions and a reference of the available environment variables.
I guess developers using Enchant just as library would first look for API documentation than expecting those information in the man page. Still, the list of environment variables in the man page is completely fine as they are also relevant for the `enchant` command line tool.

**Comment by rrthomas** [comment]
OK, thanks for the suggestion.
